name: Update Datasets

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: |
          chmod +x scripts/update-dataset.sh
          ./scripts/update-dataset.sh

      - name: Commit report
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add datasets/
          git commit -m "auto: update dataset on push"
          git push
